### ISSUE TITLE
Replace calls to panic! with Result types

### ISSUE THREAD

**Issue by jmacdonald** [trishume/syntect#98] opened 2017-08-31 02:32 UTC
After doing a quick search, there are 8 occurrences of `panic!` in syntect. It'd be great to have these errors bubbled up using `Result` types with custom errors, instead. With the existing implementation, it's awkward to handle these, and because these methods don't signal the possibility of these errors, you won't realize there's an issue until you hit a runtime panic and have to work backwards to find the source.

**Comment by trishume** [comment] 2017-08-31 02:41
Agreed, it'll be unfortunate that parsing will sometimes fail with regex compilation errors, but better than probably better than panicking. I'm unlikely to work on this myself any time soon though.

**Comment by jmacdonald** [comment] 2017-08-31 02:44
Totally fine. Custom `error-chain` error setup is still fresh in my mind, so I may tackle both this and #94 shortly.

**Comment by robinst** [comment] 2018-05-07 00:55
From discussion on https://github.com/trishume/syntect/issues/156#issuecomment-386162742:

For checking that regexes compile, we might want to do that when we load the syntaxes from the yaml files (before linking them). For patterns with placeholders, we'd just use a dummy value (`a` or whatever) before compiling them.

This should not slow down normal use cases where loading from yaml happens once, is serialized to a binary dump, and then later that dump is loaded before matching. Loading the dump would not compile the regexes until they are needed, just like the current behavior.

That gives us a much earlier (and more useful) check if there's a problematic regex in a syntax definition. Note that compiling could still fail at runtime if a dump from a previous version of syntect is loaded, and something about the regex engine changed in syntect, but that should be minimal compared to what we have now. And we could still make matching work with Results later.

**Comment by Enselic** [comment] 2022-01-08 06:59
I plan on looking into this for 5.0. This clippy command can be used to find potential panics:

```cargo clippy -- --deny clippy::panic --deny clippy::unwrap_used --deny clippy::expect_used
```

there are currently 38 of these, of which 5 are direct calls to `panic!()`.

**Comment by Canop** [comment] 2022-01-21 21:46
Related: I didn't want to use the version 5 now and I had to fix some panics because it crashed broot, so I converted them to errors in [this commit](https://github.com/Canop/syntect/commit/5c9840eab9477c3964b1a310ede4f5e3070ccc67). This commit isn't directly usable as I had to start from an old commit but I don't think it would be hard to do the same on the whole up to date codebase.

**Comment by Enselic** [comment] 2022-02-20 10:00
@Canop Thanks for sharing! I will make sure to cover all cases of `Result` that you add in that commit before I close this issue.

I will not use your API verbatim however. For example, I'm not a fan of the `CrashError` type, because:
* It is (by my estimation) not idiomatic Rust error handling
* I think it is better to be specific. For example, I plan on introducing an `ContextMissing` error for cases like #421.

If you want to embark on this journey together with me, I would appreciate your review on #424 which is one step towards resolving this issue. It sets the structure for future work on this issue by introducing a new enum `syntect::Error`.

**Comment by Enselic** [comment] 2022-03-27 10:22
I created a PR (https://github.com/trishume/syntect/pull/432) that removes all direct `panic!()` calls. I tried to carefully make all API changes you did in your commit @Canop. Please read the PR description for details. One thing to note in particular is that there seems to be a slight performance penalty (1-3%-ish) in propagating errors, but personally I think that is OK. I am curious to hear what others in this issue think.

In the PR, all direct panics are gone, and regressions are prevented with a CI check. However, I have not taken care of replacing all `.unwrap()`s and `.expect()`s with error propagation, so panics can still happen. And to be honest my mental momentum is starting to run out, so I don't think I will have the energy to take care of that. We can leave this issue open until someone else gets around to do that I suppose.

**Comment by Enselic** [comment] 2022-06-18 17:17
I consider this fixed by the 5.0.0 release. Please open new specific issues if additional changes are necessary.

**Closed by Enselic** 2022-06-18 17:17 UTC
Labels: enhancement
