### ISSUE TITLE
Rust `union` keyword doesn't seem to be recognized

### ISSUE THREAD

**Issue by cbiffle** [trishume/syntect#401] opened 2021-12-08 01:54 UTC
Hi! This might not be a syntect bug -- I'm using the crate through Zola.

I notice that the `union` keyword isn't highlighted in [the source example here](https://cliffle.com/p/dangerust/4/#type-punning-via-union), but it seems like it should be.

**Comment by Enselic** [comment] 2021-12-08 07:04
Thanks for taking the time to report a bug.

Seems to be caused by missing support in the syntax definition for Rust. https://github.com/sublimehq/Packages/blob/master/Rust/Rust.sublime-syntax does not contain the word `union`.

You might want to file a bug report with them.

Since it is out of scope of syntect to keep syntax definitions up of date, and since there is no support missing from the syntect syntax highlighting engine, I'll go ahead and close this ticket.

It is worth noting that there is interest in setting up a separate project that keeps a wide range of syntaxes up to date, see #168.

**Closed by Enselic** 2021-12-08 07:04 UTC
