### ISSUE TITLE
Constant memory usage after first use

### ISSUE THREAD

**Issue by rabite0** [trishume/syntect#251] opened 2019-06-11 22:11 UTC
I was trying to implement syntax highlighting to the previews in hunter, but I noticed that syntect drastically increased memory usage after first use. 

I guess it builds up some caches for things, I'm not sure what exactly is causing this. I don't think regexes would be this big, but maybe. 

Unfortunately it doesn't seem to be possible to drop the caches, or whatever is using that memory. In hunter's case, memory usage went from 8MB to 12MB after highlighting the first file. A bit too much for my tastes ;).

I pretty much just copied over the example code for HighlightFile, but instead of printing the lines out I saved them to a buffer.

As a workaround I'm using syntect indirectly through bat now, so it's not a big issue, but maybe it would be nice if it was possible to "uninitialize" syntect somehow.

**Comment by trishume** [comment] 2019-06-11 22:50
Yah those are regexes in the regex cache. You can in fact drop the cache but only by dropping the entire `SyntaxSet` in between highlighting things, which is basically what you're doing by running through bat anyways except with extra process overhead.

**Comment by trishume** [comment] 2019-06-11 22:54
Also a performance benefit you could get by bringing syntect in-process is only highlighting the first N lines of the file when scrolling through files to preview them, instead of the whole file. Although it's plausible you're already getting this with bat if you disconnect STDOUT and kill it after it writes out enough lines, and bat's writing is unbuffered enough.

You may also be interested in a bat feature which allows it to use ansi terminal colors for output, which it does with a special theme that uses the alpha value to signal that colors are ansi colors, and then outputs the red component as an ansi value or something, it's pretty simple to implement.

**Comment by rabite0** [comment] 2019-06-12 00:01
Thanks for the quick response.

By dropping SyntaxSet, do you mean just letting the variable go out of scope, or is there more to it? Because that's pretty much what I was doing.

Here's a minimal example:

```
use syntect::parsing::SyntaxSet;
use syntect::highlighting::{ThemeSet, Style};
use syntect::util::as_24_bit_terminal_escaped;
use syntect::easy::HighlightFile;
use std::io::BufRead;


fn main() {
    std::io::stdin().read_line(&mut String::new()).unwrap();
    hl();
    std::io::stdin().read_line(&mut String::new()).unwrap();
}


fn hl() {

    let ss = SyntaxSet::load_defaults_newlines();
    let ts = ThemeSet::load_defaults();

    let mut highlighter = HighlightFile::new("/home/project/.zshrc", &ss, &ts.themes["base16-ocean.dark"]).unwrap();
    let mut line = String::new();
    while highlighter.reader.read_line(&mut line).unwrap() > 0 {
        {
            let regions: Vec<(Style, &str)> = highlighter.highlight_lines.highlight(&line, &ss);
            println!("{}", as_24_bit_terminal_escaped(&regions[..], true));
        } // until NLL this scope is needed so we can clear the buffer after
        line.clear(); // read_line appends so we need to clear between lines
    }
}
```

When I run this in release mode it's using 1,5MB after startup, then after hl() ran it stays at 9MB. SyntaxSet should have been dropped by the time it's waiting for the second input, or am I missing something?

Also, bat actually has a --line-range option, which nicely limits its output/rendering. Performance-wise I don't really see a difference between using syntect directly and using bat. The only downside is that it's another thing to  explain/install for users.

**Comment by trishume** [comment] 2019-06-12 00:38
Hmm interesting. Syntect has one piece of global `lazy_static` state but it should be pretty small, and it's populated immediately upon creation of the `SyntaxSet` not lazily during highlighting like the regex cache. Dropping the `SyntaxSet` (by letting it go out of scope like you're doing) should drop all the large state.

One theory I have is that your memory allocator might be keeping the kernel pages held by the process for later re-use, since it doesn't see 9MB as an unreasonable amount of memory to hold on to.

**Comment by trishume** [comment] 2019-06-12 00:39
You could try using a Rust custom allocator that tracks total currently allocated bytes and then passes things on to a normal allocator. It shouldn't be too hard, there may already be a crate for it even. And that should tell you what's the fault of your memory allocator holding on to pages and what is actual state that isn't being dropped.

**Comment by Enselic** [comment] 2021-11-11 20:02
Thanks a lot for that reproduction code. That makes investigating this so much easier.

Conveniently, the [std::alloc::System docs](https://doc.rust-lang.org/std/alloc/struct.System.html) contain example code on how to track allocations and deallocations of memory.

On my system, I get that `8 541`  bytes are allocated right before `h1()` is called.
Right before `h1()` returns, `5 452 189` bytes are allocated. Both in debug and release builds.

After `h1()` returns, `152 419` bytes are allocated. And if we add this function to `ScopeRepository`:

```rust
    /// De-allocates most memory used. To be used in de-initialization uses cases.
    pub fn dealloc(&mut self) {
        // Easiest way to de-allocate is to drop old values and start over
        self.atoms = Vec::new();
        self.atom_index_map = HashMap::new();
    }
```

and call that before we return from `h1()`:

```rust
    syntect::parsing::SCOPE_REPO.lock().unwrap().dealloc();
```

only `9693` bytes are allocated after `h1()` returns. So calling `h1()` increases memory usage by `9 693 - 8 541 = 1152` *bytes*. I suspect that is caused by lazy_static fields themselves.

Also, calling `hl()` a 100 times:

```rust
    for _ in 0..100 {
        hl();
    }
```
does not accumulate allocated memory. It stays the same. So in short, everything seems to be in order.

As pointed out, that the process does not release the pages to the OS is most likely because the malloc-implementation holds on to the pages, because most likely there will be more memory allocations later.

FWIW, the code I used to draw these conclusions can be found here: https://gist.github.com/Enselic/37e55e85b88044beedd91e88b367ad75

So I would say we can close this issue. Any objections?

**Closed** 2021-11-16 15:38 UTC
