### ISSUE TITLE
Difference in highlighting some TypeScript React files (Sublime vs. Syntect)

### ISSUE THREAD

**Issue by slimsag** [trishume/syntect#97] opened 2017-08-30 05:31 UTC
Syntect fails to properly syntax highlight some TypeScript React (tsx) files in contrast to Sublime Text 3 which highlights them fine.

To reproduce this:

1. You'll need to first download Microsoft's official [TypeScriptReact.tmLanguage](https://raw.githubusercontent.com/Microsoft/TypeScript-TmLanguage/master/TypeScriptReact.tmLanguage) file and save it somewhere.
2. Convert that `.tmLanguage` file to a `.sublime-syntax` file, using Sublime Text 3's builtin `Plugin Development: Convert Syntax to .sublime-syntax` command (important: only shows up when viewing `.tmLanguage` files)
3. Save the new `.sublime-syntax` file into e.g. `testdata/Packages/TypeScript/TypeScriptReact.sublime-syntax`
4. Run `make assets`.

Alternatively, [my fork's branch here](https://github.com/slimsag/syntect/tree/issue-97) has the above steps done so you don't have to perform them. The `.sublime-syntax` file is also in the root of the repo. 

Once you've done the above or cloned my fork,

1. Save this [BasePicker.tsx](https://raw.githubusercontent.com/OfficeDev/office-ui-fabric-react/5e9fbcd5735cc185c1b2e047beb517cb9f1dbe96/packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx) test file anywhere.
2. Save [TypeScriptReact.sublime-syntax](https://raw.githubusercontent.com/slimsag/syntect/issue-97/TypeScriptReact.sublime-syntax) into e.g. `~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/` on Mac (and uninstall the TypeScript Sublime plugin, to prevent any concern over the tmLanguage -> sublime-syntax conversion potentially being the issue).

When the file is viewed in Sublime, it looks like this:

![image](https://user-images.githubusercontent.com/3173176/29856488-08f66eb4-8d08-11e7-9515-40c5a61bbde0.png)

In contrast, the HTML rendered by `cargo run --example synhtml ./BasePicker.tsx > out.html` ends up looking like this:

![image](https://user-images.githubusercontent.com/3173176/29856612-eb9788de-8d08-11e7-999b-0444d0bf3de0.png)

Of course, the above two look different due to the theme in use, but notice that even just in the syntect result alone there are two different colors in use for the attributes:

![image](https://user-images.githubusercontent.com/3173176/29856639-27c0dc52-8d09-11e7-9e1f-20bbcf0537f2.png)

I found that changing this line of code to remove the addition operator:

```diff
                suggestedDisplayValue={ suggestedDisplayValue }
-               aria-activedescendant={ 'sug-' + this.suggestionStore.currentIndex }
+               aria-activedescendant={ this.suggestionStore.currentIndex }
                aria-owns='suggestion-list'
```

Fixes the highlighting in Syntect:

![image](https://user-images.githubusercontent.com/3173176/29856691-74f2b090-8d09-11e7-974f-8470244c2365.png)

If it wasn't for Sublime rendering this file with the same sublime-syntax, I would assume the syntax file was broken somehow -- but given the difference between Sublime and Syntect's rendering, I assume this must be a bug in Syntect (but I do not understand Syntect well enough to even begin tracking it down :) )

**Comment by trishume** [comment] 2017-08-30 13:21
Interesting, I wonder if this is related to the ASP syntax tests still failing. I never got around to fixing all of those. See #51.

**Comment by robinst** [comment] 2018-02-12 01:30
(For anyone wondering, v2.0.0 still has this issue, just tested.)

**Comment by robinst** [comment] 2018-04-26 04:01
Was wondering whether #146 changes this, it doesn't.

But what I noticed is that `cargo run --example syncat` doesn't have the same problem, only `synhtml`. I wonder what they do differently, it might give a clue as to what the problem is. But it also might just be a bug in syncat or synhtml :)..

**Comment by trishume** [comment] 2018-04-26 18:26
@robinst huh weird, yah probably a bug in synhtml.

**Comment by trishume** [comment] 2018-04-28 15:00
Okay I diagnosed this hoping to fix it before the next release, unfortunately it's tricky.

Basically `synhtml` uses the `nonewlines` mode, which uses hacky regex rewriting, which is incomplete. The `\s` metacharacter matches newlines and we don't do anything about it.

That causes this rule to fail to match on the `\s+` in this regex:
```yaml
  jsx-tag-in-expression:
    - match: |-
        (?x)
        (?<=[({\[,?=>:*]|&&|\|\||\?|\Wreturn|^return|\Wdefault|^)\s*
        (?!<\s*[_$[:alpha:]][_$[:alnum:]]*((\s+extends\s+[^=>])|,)) # look ahead is not type parameter of arrow
        (?=(<)\s*
        ([_$a-zA-Z][-$\w.]*(?<!\.|-))
        (?=\s+(?!\?)|/?>))
```

A minimal test case file that differs in parsing (in parsing on the first line, in highlighting with base16-ocean-dark only on the second) is:
```html
<div
ref="hi"
```

For now the workaround is just to use newlines mode. It's just better.

**Comment by robinst** [comment] 2018-04-29 00:27
Ah nice, that makes sense. Should we also make synhtml use newlines mode by default?

**Comment by trishume** [comment] 2018-04-29 01:35
@robinst probably, and maybe in the mean time change the docs to suggest that nonewlines is known to be mostly working but a little bit broken and point to this issue.

I wonder if eventually a mode could be added to fancy-regex to hallucinate a `\n` at the end of strings, although that may run into the problem of `regex` not supporting it.

**Comment by Enselic** [comment] 2021-11-10 05:40
A similar problem still exists in latest syntect master with the latest TypeScriptReact.tmLanguage:

```
cargo run --example syncat -- ~/Downloads/BasePicker.tsx --no-newlines
```

<img width="604" alt="Screen Shot 2021-11-10 at 06 33 43" src="https://user-images.githubusercontent.com/115040/141055814-52339d7f-e5a3-4461-b608-900f294b94fb.png">

However, as before, not using `nonewlines` behaves correct:

```
cargo run --example syncat -- ~/Downloads/BasePicker.tsx
```

<img width="605" alt="Screen Shot 2021-11-10 at 06 36 35" src="https://user-images.githubusercontent.com/115040/141056089-08150409-09da-4264-93bc-c7c51c0a8927.png">

And by now there is clear [documentation](https://docs.rs/syntect/4.6.0/syntect/parsing/struct.SyntaxSet.html#method.load_defaults_nonewlines) that avoiding `nonewlines` is recommended.

So I think we can go ahead and close this issue. Feel free to reopen if you disagree, of course.

**Closed by Enselic** 2021-11-10 05:40 UTC
