### ISSUE TITLE
Build failed for onig

### ISSUE THREAD

**Issue by elgunhuseynli** [trishume/syntect#264] opened 2019-09-28 04:18 UTC
Examples aren't compiling on Windows 10.

```
Compiling onig_sys v69.2.0
error: failed to run custom build command for `onig_sys v69.2.0`
...
--- stdout
cargo:warning=couldn't execute `llvm-config --prefix` (error: The system cannot find the file specified. (os error 2))
cargo:warning=set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable
```

**Comment by elgunhuseynli** [comment] 2019-09-28 04:23
Oniguruma is regex library written in C. Why not just use Rust's own regex library? So we don't get build errors like that.

**Comment by keith-hall** [comment] 2019-09-28 08:38
https://github.com/rust-onig/rust-onig/issues/109

> Why not just use Rust's own regex library?

see https://github.com/trishume/syntect/issues/12

**Comment by trishume** [comment] 2020-03-29 22:37
See the new pure-Rust `fancy-regex` mode introduced in [v4.0.0](https://github.com/trishume/syntect/pull/270) to avoid this issue!

Still hoping that onig's build will eventually improve but for now `fancy-regex` is a good option.

**Comment by Enselic** [comment] 2021-10-04 12:16
Duplicate of #12

**Comment by Enselic** [comment] 2021-10-04 12:16
This issue can be closed with motivation:

Effectively a duplicate of #12

**Closed** 2021-10-04 14:10 UTC
