### ISSUE TITLE
Release new version with updated deps?

### ISSUE THREAD

**Issue by ignatenkobrain** [trishume/syntect#204] opened 2018-09-02 18:20 UTC
We want to package syntect in Fedora, but some of deps are old in released version. Could you please release a new version with those fixes?

**Comment by robinst** [comment] 2018-09-03 05:49
A new major release is planned soon. On master, the dependencies should be up-to-date. Would you mind checking if master is good?

**Comment by trishume** [comment] 2018-10-03 01:43
Because of the way Cargo and semver works it should be fine to use syntect with any newer minor versions. Trouble should only arise with newer major versions, are there are new major versions master is missing that you need?

**Comment by robinst** [comment] 2018-10-04 04:59
Maybe what would really solve @ignatenkobrain's problem is if we started to include a `Cargo.lock` in the repository with the newest versions? AFAIK we could do that and it would not affect projects that pull in syntect as a dependency, as cargo skips the lock file in that case. It would only affect building syntect from a checkout.

But that's just a guess, I'm not familiar with how Fedora's packaging works.

**Comment by trishume** [comment] 2018-10-05 02:51
I'm not sure I'm understanding what's going wrong correctly but it sounds like your package importer may not behave ideally. It should accept any newer minor version of the dependencies and should not fail if the `Cargo.toml` lists an older minor version, only an older major version. The `Cargo.toml` version means the oldest point release of the major version that has all the features needed.

If the problem is actually us using an outdated major version even on `master`, let us know.

**Comment by ignatenkobrain** [comment] 2018-10-05 05:58
No, in master everything is good. Problem is with latest version on crates.io

**Comment by trishume** [comment] 2018-10-13 07:08
Now released as `v3.0.0`

**Closed by trishume** 2018-10-13 07:08 UTC
