### ISSUE TITLE
Semver violation in v4.7.0 and v4.7.1

### ISSUE THREAD

**Issue by Emoun** [trishume/syntect#402] opened 2021-12-26 16:14 UTC
The 4.7.0 release violates semver. See:
* sharkdp/bat#1991
* dtolnay/cargo-expand#122

**Comment by trishume** [comment] 2021-12-26 16:44
Ah crud, I didn't notice the moving APIs behind a feature thing. I can yank the release and publish again as 5.0.0

**Comment by trishume** [comment] 2021-12-26 16:45
I yanked 4.7.0 from crates.io

**Comment by trishume** [comment] 2021-12-26 16:54
I'm going to take a look at the features to see if I can rejigger them to be semver-compatible, but otherwise I'll just publish this release as 5.0.0 with migration notes for features.

**Comment by Enselic** [comment] 2021-12-26 18:21
@trishume I'm so sorry to cause troubles for you 🙁I'm not at home at the moment. If I were, I would work on this with highest prio.

Since v4.7.0 is yanked there is no rush to make a new release I think? In a few days I'll have time to try I come up with a solution. One option on the table is to revert the change so we don't have to do a major bump. But hopefully I can come up with a solution.

**Comment by trishume** [comment] 2021-12-26 21:17
@Enselic yup no rush, and don't worry about it, it wasn't out for long and I did look over those changes and not notice the implications of the features added either. I may or may not have time to look at things myself, we'll see who gets there first.

Another potential option is to first release a minor version with compatible features but hopefully load time improvements, then do a major version bump so that people on the old version still get the improvements but maybe not some other things.

**Comment by Enselic** [comment] 2021-12-28 20:23
This should be fixed by #403.

I could reproduce the `plist-load` related build error locally, and can confirm that the PR fixes the build in that case.

It also fixes a semver problem related to the `parsing` feature that has not been reported yet, but that I can confirm existed. Most easily triggered by doing `cargo build --no-default-features --features minimal-application` in `bat`.

**Comment by Enselic** [comment] 2022-01-03 08:41
I am terribly sorry, but we need to yank v4.7.1 and reopen this issue. See https://github.com/trishume/syntect/pull/403#issuecomment-1003940363.

So so sorry about this :(

**Comment by Enselic** [comment] 2022-01-06 08:19
v4.7.1 has also been yanked now, so the urgent problem this issue is about has been taken care of. Closing.

**Closed by Enselic** 2022-01-06 08:19 UTC
