### ISSUE TITLE
Build not working

### ISSUE THREAD

**Issue by codeyash** [trishume/syntect#89] opened 2017-07-08 07:48 UTC
clone repo
    git submodule update --init
    cargo build
make[2]: *** [CMakeFiles/onig.dir/src/regext.c.o] Error 1
In file included from /home/yash/.cargo/registry/src/github.com-1ecc6299db9ec823/onig_sys-64.0.0/oniguruma/src/regparse.h:32:0,
                 from /home/yash/.cargo/registry/src/github.com-1ecc6299db9ec823/onig_sys-64.0.0/oniguruma/src/regcomp.c:30:
/home/yash/.cargo/registry/src/github.com-1ecc6299db9ec823/onig_sys-64.0.0/oniguruma/src/regint.h:667:9: error: unknown type name ‘intptr_t’

Please let me know how I can fix this or is it bug?

Thank you for your work on this great library :)

**Comment by codeyash** [comment] 2017-07-08 07:51
In file included from /home/yash/.cargo/registry/src/github.com-1ecc6299db9ec823/onig_sys-64.0.0/oniguruma/src/reggnu.c:30:0:
/home/yash/.cargo/registry/src/github.com-1ecc6299db9ec823/onig_sys-64.0.0/oniguruma/src/regint.h:667:9: error: unknown type name ‘intptr_t’
 typedef intptr_t OnigStackIndex;
         ^
make[2]: *** [CMakeFiles/onig.dir/src/reggnu.c.o] Error 1
In file included from /home/yash/.cargo/registry/src/github.com-1ecc6299db9ec823/onig_sys-64.0.0/oniguruma/src/regext.c:30:0:
/home/yash/.cargo/registry/src/github.com-1ecc6299db9ec823/onig_sys-64.0.0/oniguruma/src/regint.h:667:9: error: unknown type name ‘intptr_t’
 typedef intptr_t OnigStackIndex;
         ^
make[2]: *** [CMakeFiles/onig.dir/src/regext.c.o] Error 1
make[2]: *** [CMakeFiles/onig.dir/src/regparse.c.o] Error 1
make[2]: *** [CMakeFiles/onig.dir/src/regcomp.c.o] Error 1
make[2]: *** [CMakeFiles/onig.dir/src/regexec.c.o] Error 1
make[1]: *** [CMakeFiles/onig.dir/all] Error 2
make: *** [all] Error 2
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2

build script failed, must exit now', /home/yash/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.24/src/lib.rs:593
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by codeyash** [comment] 2017-07-08 07:54
If you don't mind why we used onigurum  and why not default https://github.com/rust-lang/regex instead?

**Comment by codeyash** [comment] 2017-07-08 14:16
I reported on onig as well 

https://github.com/rust-onig/rust-onig/issues/44

**Comment by cmyr** [comment] 2017-07-08 15:38
@codeyash what platform are you on, what version of rustc are you using, and what version of oniguruma do you have installed?

Rust's regex implementation doesn't support some features regex features (backtracking in particular) that are used in a bunch of syntax definitions.

**Comment by codeyash** [comment] 2017-07-08 16:16
Linux mint 18
rustc 1.20.0-nightly (05b579766 2017-07-01)
binary: rustc
commit-hash: 05b5797664d6aeaa0c7d0606610f336fe0b57e97
commit-date: 2017-07-01
host: x86_64-unknown-linux-gnu
release: 1.20.0-nightly
LLVM version: 4.0

oniguruma : I don't know. It's automatically used by cargo during build command.

Okay.

**Comment by cmyr** [comment] 2017-07-08 16:30
@codeyash the `onig` crate only supplies bindings to the `libonig` C library. Try installing `libonig-dev` through `apt`.

**Comment by trishume** [comment] 2017-07-08 17:40
This was probably caused by the new version of the `onig` crate that seems to have broken a bunch of things. https://github.com/rust-onig/rust-onig/issues/42 is a different error but also started happening with that update.

If it isn't fixed shortly I'll just push a new version of syntect that pins `onig` to an old version.

**Comment by iwillspeak** [comment] 2017-07-09 16:42
Sorry about this. I'm having trouble reproducing the build issue locally. I suspect it is a change made in oniguruma itself which is responsible for the build failure. If I can reproduce the failure I'll have a go at seeing if there's anything I can do to fix it.

**Comment by robinst** [comment] 2018-02-12 00:50
@codeyash: Can you please try and see if the issue is still there for you with the newest version of syntect?

**Comment by codeyash** [comment] 2018-02-27 06:51
It's fixed. :)

**Comment by robinst** [comment] 2018-02-28 00:41
Thanks, closing this issue then :)!

**Closed by robinst** 2018-02-28 00:41 UTC
